[mgr]
show_hidden = true
linemode = "custom_mtime"

[preview]
tab_size = 2

[opener]
edit = [
  { run = 'open "$@"',  desc = "Open", for = "macos" },
  { run = '${EDITOR:-vi} "$@"', desc = "Open in $EDITOR", block = true },
  { run = 'nvim "$@"', desc = "Open in nvim", block = true },
  { run = 'neovide "$@"', block = false, orphan = true, desc = "Open in Neovide" },
  { run = 'code "$@"', block = false, orphan = true, desc = "Open in VSCode" },
]
open = [
  { run = 'open "$@"',  desc = "Open", for = "macos" },
]

[open]
append_rules = [
  # Text
  # add "open" to the list
  { mime = "text/*", use = [ "edit", "open", "reveal" ] },
]
