return {
  "nvim-treesitter/nvim-treesitter",
  -- version = "*", -- releases are not really updated
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  lazy = false,
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "json",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "xml",
      "html",
      "css",
      "scss",
      "graphql",
      "jsdoc",
      "markdown",
      "markdown_inline",
      "vue",
      -- "mermaid",
      "python",
      "toml",
      "bash",
      "lua",
      "vim",
      "vimdoc",
      "dockerfile",
      "gitignore",
      "diff",
      "terraform",
      "hcl",
      "java",
      "sql",
      "properties",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-space>",
        node_incremental = "<C-space>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
  },
}
