return {
  "nvim-treesitter/nvim-treesitter",
  opts = {

    ensure_installed = {
      "json",
      "javascript",
      "typescript",
      "tsx",
      "yaml",
      "xml",
      "html",
      "css",
      "scss",
      "graphql",
      "jsdoc",
      "markdown",
      "markdown_inline",
      -- "mermaid",
      "python",
      "toml",
      "bash",
      "lua",
      "vim",
      "vimdoc",
      "dockerfile",
      "gitignore",
      "diff",
      "terraform",
      "hcl",
      "java",
    },
  },
}
