local hotkey = require("hs.hotkey")
local window = require("hs.window")

-- move between windows
local windowNavLeader = { "alt", "ctrl" }
hotkey.bind(windowNavLeader, "h", function()
  local win = window.focusedWindow()
  win:focusWindowWest()
end)
hotkey.bind(windowNavLeader, "j", function()
  local win = window.focusedWindow()
  win:focusWindowSouth()
end)
hotkey.bind(windowNavLeader, "k", function()
  local win = window.focusedWindow()
  win:focusWindowNorth()
end)
hotkey.bind(windowNavLeader, "l", function()
  local win = window.focusedWindow()
  win:focusWindowEast()
end)
